axway_oauth2:
  client_id: 5b021b47-4a31-4ec1-9182-578ab3fbe1fe
  client_secret: e95de26c-2de2-4c9c-b0ed-207ef16f9ac4
  grant_type: authorization_code
  redirect_uri: http://localhost:5555/authorization
  response_type: code
  scope: resource.WRITE,resource.READ
  url_authorize: https://127.0.0.1:8089/api/oauth/authorize
server:
  port: 5555
